[package]
name = "snx"
description = "an experimental web framework"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
serde = { version = "1.0.210", features = ["derive"] }
toml = "0.8.19"
