[package]
name = "blog"
version = "0.1.0"
edition = "2021"

[lib]
name = "blog"
path = "src/lib/lib.rs"

[[bin]]
name = "blog"
path = "src/bin/main.rs"

[dependencies]
snx = { path = "../../" }
tokio = { version = "1.40.0", features = ["rt", "rt-multi-thread", "macros"] }
